In [2]:
import numpy as np
a=np.random.randn(5,1)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[[-0.50774718]
 [-0.34841074]
 [ 0.24275687]
 [-0.82015441]
 [ 0.25278728]]
(5, 1)
[[-0.50774718 -0.34841074  0.24275687 -0.82015441  0.25278728]]
[[ 0.2578072   0.17690457 -0.12325912  0.41643109 -0.12835203]
 [ 0.17690457  0.12139004 -0.0845791   0.2857506  -0.0880738 ]
 [-0.12325912 -0.0845791   0.0589309  -0.19909812  0.06136585]
 [ 0.41643109  0.2857506  -0.19909812  0.67265326 -0.2073246 ]
 [-0.12835203 -0.0880738   0.06136585 -0.2073246   0.06390141]]


In [3]:
assert(a.shape==(5,1))

In [22]:
b=np.random.randn(10,10)
c=np.random.randn(10,2)
print(c)
print(b)

[[ 0.66874893 -0.68915029]
 [ 0.39791233  0.71059076]
 [-1.0377646   1.16806945]
 [-2.48090212 -0.65852386]
 [-1.26225634 -1.06191054]
 [ 0.50923676 -0.48354439]
 [ 0.5407535  -2.18329408]
 [ 1.30527662 -0.7503044 ]
 [-0.63230246 -1.11934767]
 [-1.3166078  -1.39493505]]
[[ 0.3287854  -1.08238782 -0.45586964  0.23707491  0.84359144 -0.86703962
   1.05365581  0.61335903  0.30769694 -0.76576428]
 [-0.50100748 -1.98341339 -1.21974003 -0.48741647 -0.50536705  0.14371528
  -1.71294263 -0.33675751 -1.13874381 -0.26154573]
 [-0.8560817   0.5397473  -0.11702824 -1.14662437 -0.68499223  0.07090643
   0.50964145  2.24795143 -1.59245994  2.13299011]
 [ 1.42424234 -0.10592782  0.75455041 -0.07475654  0.77111317  0.35923141
  -1.09996533  1.16954789  1.08070016 -0.43369881]
 [-0.85080498  1.34847584  0.86892052 -1.11546305 -0.25174597 -0.49974644
   1.57605223  2.10441249  0.07166449 -0.42489441]
 [ 1.28615438  0.36244555  0.62871485  1.33408133  0.91269206 -0.70022081
  -0.8892786  -1.05576334  0.0

In [23]:
d=np.dot(b,c)
print(d)

[[ 0.35177303 -4.1977656 ]
 [ 1.76039281  3.93128808]
 [ 4.91751667 -1.7072065 ]
 [ 0.34177514 -0.19941632]
 [ 6.00970046 -0.70440598]
 [-5.74678896  1.93153885]
 [-3.63614494  4.41027701]
 [-2.7258331   4.83107545]
 [ 0.64218279 -7.6049658 ]
 [-4.16083594  8.01078028]]
